import { Inter } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import Head from "next/head";
import { icon } from "@fortawesome/fontawesome-svg-core";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "NGS | Leão e Associados",
  description: "Generated by create next app",
  icon: "./logoNGS.png",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
